name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Extract project files
      run: |
        if [ -f "cobudget-github-simple.tar.gz" ]; then
          tar -xzf cobudget-github-simple.tar.gz
        elif [ -f "cobudget-github-ready.tar.gz" ]; then
          tar -xzf cobudget-github-ready.tar.gz
        fi
    
    - name: Create web app build
      run: |
        mkdir -p dist
        
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
            <title>CoBudget - Expense Tracker</title>
            <style>
              body { 
                margin: 0; 
                font-family: -apple-system, BlinkMacSystemFont, sans-serif;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
              }
              .container { 
                display: flex; 
                justify-content: center; 
                align-items: center; 
                height: 100vh;
                flex-direction: column;
                text-align: center;
                padding: 20px;
              }
              .logo {
                font-size: 2.5em;
                font-weight: bold;
                margin-bottom: 20px;
              }
              .loading {
                font-size: 1.2em;
                margin-bottom: 30px;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="logo">💰 CoBudget</div>
              <div class="loading">Loading your expense tracker...</div>
            </div>
            <script>
              setTimeout(() => {
                window.location.href = 'https://cobudget.replit.app';
              }, 3000);
            </script>
          </body>
        </html>
        EOF
    
    - name: Initialize Capacitor if needed
      run: |
        if [ ! -d "android" ]; then
          npx @capacitor/cli@latest create-app cobudget com.cobudget.app --web-dir=dist
          cd cobudget
          npx cap add android
          cp -r android ../
          cd ..
        fi
    
    - name: Sync Capacitor
      run: npx cap sync android
    
    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cobudget-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
